### ISSUE TITLE
How to add this to an existing project ?

### ISSUE THREAD

**Issue by GhaziBenDahmane** [6pm/react-heatmap#1]
I have a react project that i would like to install this on , does it exist on npm ? how do i add it ( since copying the source signals an error in the style.scss file

**Comment by 6pm** [comment]
Hello. Sorry for long time no answering. This mail I got in spam-list.
This component is not exists in npm. You must download and put into your project. 
Do you have a loader for scss styles?

**Comment by GhaziBenDahmane** [comment]
No worries i fixed my problems and just compiled the scss into css before copying it.
Did some changes to the component to fill my needs tho , thanks a lot for helping ( just added some props to disable navigation and legend , since i didn't need both of those )
